config/routes.rb
Rails.application.routes.draw do

  resources :enrollments do
    get :my_students, on: :collection
  end

  devise_for :users

  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons do
      put :sort
    end
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]

  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'


  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end

  root "home#index"
  get 'privacy_policy', to: "static_pages#privacy_policy"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
  end

  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def analytics
    if current_user.has_role?(:admin)

      else
        redirect_to root_path, alert: "You are not authorized to access this page"
      end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do
  E-Learning
  \|
  Activity

%h3
  .text-center
    Activity
    .badge.badge-info
      = @activities.count
%p

%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      = activity.created_at.strftime('%d-%m-%Y %H:%m')
      (#{time_ago_in_words(activity.created_at)})
      = model_label(activity.trackable_type)
      = activity.trackable_type
      - if activity.trackable_type == "Lesson"
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          Lesson was deleted
      - else
        = link_to activity.trackable, activity.trackable
      = crud_label(activity.key.match(/\.(.*)/)[1])
      by
      = link_to activity.owner, user_path(activity.owner)
      - if activity.parameters.any?
        = activity.parameters

!= pagy_bootstrap_nav(@pagy)
%br

app/views/home/analytics.html.haml
- content_for :title do
  E-Learning
  \|
  Analytics


%h4.text-center
  New users per day
= line_chart charts_users_per_day_path
%p

%h4.text-center
  New enrollments per day
= column_chart charts_enrollments_per_day_path
%p

%h4.text-center
  Most enrolled courses
= bar_chart charts_course_popularity_path
%p

%h4.text-center
  Most paid courses
= bar_chart charts_money_makers_path
%p

app/views/home/index.html.haml
- content_for :title do
  E-Learning
  \|
  Online Courses - Learn Anything, On Your Schedule

.jumbotron
  .display-4
    What do you want to learn today?

  .p-4
  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}

.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = pluralize(Course.approved.published.count, 'online courses')
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

%p

- if current_user
  %h2
    .fa.fa-user-graduate
    Continue Learning
  .card-columns
    - @purchased_courses.each do |course|
      = render 'courses/course', course: course
  .text-right
    = link_to 'All my purchased courses', purchased_courses_path
  %hr

%h2
  .fa.fa-chart-line
  Popular courses
.card-columns
  - @popular.each do |course|
    = render 'courses/course', course: course

.text-right
  = link_to 'More popular courses', courses_path(courses_search: {s: 'enrollments_count desc'})
%hr
%h2
  .fa.fa-star
  Top rated courses
.card-columns
  - @top_rated.each do |course|
    = render 'courses/course', course: course
.text-right
  = link_to 'Best rated courses', courses_path(courses_search: {s: 'average_rating desc'})

%hr
%h2
  .fa.fa-clock
  Latest courses
.card-columns
  - @latest.each do |course|
    = render 'courses/course', course: course
.text-right
  = link_to 'More new courses', courses_path(courses_search: {s: 'created_at desc'})

%hr
%h2
  .fa.fa-comment
  What our students have to say
.card-columns
  - @latest_good_reviews.each do |enrollment|
    = render 'enrollments/enrollment', enrollment: enrollment